name: deploy-workflow
on: [push] # [A]
jobs:
  deploy-job:
    runs-on: ubuntu-latest # [B]
    steps:
      - uses: actions/checkout@v2 # [C]
      - uses: actions/setup-node@v2 # [D]
        with:
          node-version: '13'
      - run: npm install # [E]